services:
  backend:
    #image: backend:latest
    image: avengersa/backend:latest
    ports:
      - "3000:3000"
    env_file:
      - backend/.env

  frontend:
    #image: frontend:latest
    image: avengersa/frontend:latest
    ports:
      - "3001:3000"
    env_file:
      - frontend/.env
    environment:
      NEXT_PUBLIC_API_URL: "http://52.47.126.104:3000"
    depends_on:
      - backend  
