/*pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "avengersa/backend"
        DOCKER_TAG = "v0"
        DOCKER_CREDENTIALS_ID = 'docker-hub-credentials' 
    }

  /*  stages {

        stage('Build Docker Image') { 
            steps {
                script {
                    dir('backend') {
                        docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}", ".")
                    }
                }
            }
        }
 
        stage('Push Docker Image') {
            steps {
                script {
                    dir('backend') {
                        docker.withRegistry('https://registry.hub.docker.com', "${DOCKER_CREDENTIALS_ID}") {
                            def image = docker.image("${DOCKER_IMAGE}:${DOCKER_TAG}")
                            image.push()
                        }
                    }
                }
            }
        }
    }
}
*/
pipeline {
    agent any

    environment {
        SONAR_TOKEN = credentials('token-git-jenkins') // ID de vos credentials Jenkins  
        SONAR_HOST_URL = 'https://sonarcloud.io'
        SONAR_ORGANIZATION = 'radomala' // Votre organisation SonarCloud  
        PROJECT_KEY = 'mornings_news_backend' // Clé de votre projet  
    }

    stages {
        stage('Clone Repository') {
            steps {
                // Clonez votre dépôt depuis Git  
                git branch: 'romeo_news', credentialsId: 'token-git-jenkins', url: 'https://github.com/radomala/mornings_news.git' // Remplacez par l'URL de votre dépôt  
            }
        }

        stage('SonarCloud Analysis') {
            steps {
                script {
                    // Exécution de SonarScanner  
                    sh """
                    sonar-scanner \
                      -Dsonar.organization=${SONAR_ORGANIZATION} \
                      -Dsonar.projectKey=${PROJECT_KEY} \
                      -Dsonar.sources=. \
                      -Dsonar.host.url=${SONAR_HOST_URL} \
                      -Dsonar.login=${SONAR_TOKEN}
                    """
                }
            }
        }
    }
}