pipeline {
    agent any

    environment {
        // Variables pour Docker Hub
        DOCKER_IMAGE = "radomala/backend" // Remplacez par votre nom d'utilisateur Docker Hub et le nom de l'image souhaitée
        DOCKER_TAG = "latest" // Utilisez un tag unique basé sur `GIT_COMMIT` ou `BUILD_NUMBER` si nécessaire
        DOCKER_CREDENTIALS_ID = 'docker-hub-credentials' // ID des credentials Docker Hub dans Jenkins
    }

    stages {
        //stage('Clone Repository') {
        //    steps {
        //        git branch: 'main', credentialsId: 'token-git-jenkins', url: 'https://github.com/radomala/morning-news.git'
        //    }
        //}

        stage('Build Docker Image') { 
            steps {
                script {
                   // dir('backend') {
                        docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}", "--build-arg NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL} .")
                   // }
                }
            }
        }
 
        stage('Push Docker Image') {
            steps {
                script {
                    //dir('backend') {
                        docker.withRegistry('https://registry.hub.docker.com', "${DOCKER_CREDENTIALS_ID}") {
                            def image = docker.image("${DOCKER_IMAGE}:${DOCKER_TAG}")
                            image.push()
                        }
                   // }
                }
            }
        }
    }
}
