pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "avengersa/backend"
        DOCKER_TAG = "latest"
        DOCKER_CREDENTIALS_ID = 'docker-hub-credentials' 
    }

    stages {

        stage('backend') {
            steps {
                echo 'Début du stage Frontend'
                // Ajoutez ici d'autres étapes pour le frontend si nécessaire
                echo 'Fin du stage Frontend'
            }
        }
        /*
        stage('Build Docker Image') { 
            steps {
                script {
                    dir('backend') {
                        docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}", ".")
                    }
                }
            }
        }
 
        stage('Push Docker Image') {
            steps {
                script {
                    dir('backend') {
                        docker.withRegistry('https://registry.hub.docker.com', "${DOCKER_CREDENTIALS_ID}") {
                            def image = docker.image("${DOCKER_IMAGE}:${DOCKER_TAG}")
                            image.push()
                        }
                    }
                }
            }
        }
        */
    }
}
